spring.application.name=lolorest
spring.datasource.url=jdbc:postgresql://localhost:5489/lolorest_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
